FROM nvcr.io/nvidia/l4t-tensorflow:r32.4.4-tf2.3-py3

RUN apt-get update && \
   apt-get install -y --no-install-recommends \
   libffi-dev libssl1.0-dev

COPY requirements_tf.txt /tmp/requirements_tf.txt
RUN pip3 install -r /tmp/requirements_tf.txt --verbose
